name: Android Debug Build

on:
  push:
    branches: [ "main", "alpha/**" ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          sdkmanager --install "platforms;android-34" "platform-tools" "build-tools;34.0.0"
          yes | sdkmanager --licenses

      - name: Build Debug APK with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.7
          arguments: :app:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
